version: '2'
services:
    laminas:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
         - "8080:80"
        volumes:
         - .:/var/www
        links:
          - database
    database:
        build: 
          context: "./bin/${DATABASE}"
        container_name: '${COMPOSE_PROJECT_NAME}-database'
        restart: 'always'
        ports:
          - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
        volumes: 
          - ${MYSQL_DATA_DIR}:/var/lib/mysql
          - ${MYSQL_LOG_DIR}:/var/log/mysql
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: '${COMPOSE_PROJECT_NAME}-phpmyadmin'
        links:
          - database
        environment:
          PMA_HOST: database
          PMA_PORT: 3306
          PMA_USER: root
          PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
          - '${HOST_MACHINE_PMA_PORT}:80'
        volumes: 
          - /sessions
          - ${PHP_INI}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
